/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    homepage: Homepage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    homepage: HomepageSelect<false> | HomepageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Photos and the hero film. Files are stored in Vercel Blob.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describes the image for screen readers and search engines. Leave empty for videos and purely decorative backgrounds.
   */
  alt?: string | null;
  _objectKey?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  _objectKey?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Everything on the landing page, one tab per section, in page order.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage".
 */
export interface Homepage {
  id: number;
  hero: {
    /**
     * The small line above the headline.
     */
    tag?: string | null;
    /**
     * Each line animates in separately. Keep to three lines at most.
     */
    heading: string;
    sub?: string | null;
    primaryCta: {
      label: string;
      message: string;
    };
    /**
     * Scrolls to the sizes and pricing section.
     */
    secondaryCtaLabel?: string | null;
    /**
     * The still shown before the film loads and on slow connections.
     */
    poster?: (number | null) | Media;
    /**
     * Short looping film without sound. Keep it under about 3 MB.
     */
    video?: (number | null) | Media;
  };
  /**
   * The row of counted-up numbers under the hero.
   */
  figures?:
    | {
        /**
         * e.g. RM
         */
        prefix?: string | null;
        value: number;
        /**
         * e.g. saiz
         */
        suffix?: string | null;
        caption: string;
        id?: string | null;
      }[]
    | null;
  work: {
    /**
     * The small red label above the heading.
     */
    eyebrow?: string | null;
    /**
     * A new line here is a line break on the page.
     */
    heading: string;
    lede?: string | null;
    items?:
      | {
          title: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    /**
     * To link a phrase to WhatsApp write [phrase](wa:message to pre-fill). For a normal link write [phrase](https://address).
     */
    note?: string | null;
  };
  moment: {
    label?: string | null;
    text: string;
    image?: (number | null) | Media;
  };
  sizes: {
    /**
     * The small red label above the heading.
     */
    eyebrow?: string | null;
    /**
     * A new line here is a line break on the page.
     */
    heading: string;
    lede?: string | null;
    /**
     * The single source for sizes and prices: the size cards, both enquiry forms, the WhatsApp messages and the prices Google reads all come from here. Prices quoted in other text, such as the hero paragraph and the FAQ answers, are edited separately.
     */
    items: {
      /**
       * e.g. Tong Kecil
       */
      name: string;
      /**
       * e.g. Kecil
       */
      shortName: string;
      price: number;
      /**
       * The bin outline on the card is drawn to this height.
       */
      heightFt: number;
      widthFt: number;
      lengthFt: number;
      capacityM3: number;
      /**
       * One line on the card: what this size is for.
       */
      hint?: string | null;
      uses?:
        | {
            text: string;
            id?: string | null;
          }[]
        | null;
      image?: (number | null) | Media;
      isDefault?: boolean | null;
      id?: string | null;
    }[];
    /**
     * The line under the price, saying what it includes.
     */
    priceNote?: string | null;
    /**
     * Longest rental offered in the enquiry forms.
     */
    maxRentalDays: number;
    help: {
      title?: string | null;
      text?: string | null;
      cta: {
        label: string;
        message: string;
      };
    };
  };
  process: {
    /**
     * The small red label above the heading.
     */
    eyebrow?: string | null;
    /**
     * A new line here is a line break on the page.
     */
    heading: string;
    steps?:
      | {
          title: string;
          text?: string | null;
          image?: (number | null) | Media;
          id?: string | null;
        }[]
      | null;
  };
  why: {
    /**
     * The small red label above the heading.
     */
    eyebrow?: string | null;
    /**
     * A new line here is a line break on the page.
     */
    heading: string;
    lede?: string | null;
    reasons?:
      | {
          title: string;
          text?: string | null;
          id?: string | null;
        }[]
      | null;
    crew?:
      | {
          image: number | Media;
          caption?: string | null;
          id?: string | null;
        }[]
      | null;
    credsLabel?: string | null;
    creds?:
      | {
          name: string;
          /**
           * e.g. Lapangan terbang
           */
          type?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  coverage: {
    /**
     * The small red label above the heading.
     */
    eyebrow?: string | null;
    /**
     * A new line here is a line break on the page.
     */
    heading: string;
    lede?: string | null;
    baseName: string;
    baseTag?: string | null;
    /**
     * Every other town served, besides the base. The list fills the two scrolling rows (first half on top), both enquiry forms and the areas Google reads.
     */
    areas?:
      | {
          name: string;
          id?: string | null;
        }[]
      | null;
    /**
     * To link a phrase to WhatsApp write [phrase](wa:message to pre-fill). For a normal link write [phrase](https://address).
     */
    note?: string | null;
    background?: (number | null) | Media;
  };
  faq: {
    /**
     * The small red label above the heading.
     */
    eyebrow?: string | null;
    /**
     * A new line here is a line break on the page.
     */
    heading: string;
    /**
     * Shown on the page and sent to Google as FAQ structured data.
     */
    items?:
      | {
          question: string;
          /**
           * To link a phrase to WhatsApp write [phrase](wa:message to pre-fill). For a normal link write [phrase](https://address).
           */
          answer: string;
          id?: string | null;
        }[]
      | null;
  };
  booking: {
    /**
     * The small red label above the heading.
     */
    eyebrow?: string | null;
    /**
     * A new line here is a line break on the page.
     */
    heading: string;
    points?:
      | {
          text: string;
          id?: string | null;
        }[]
      | null;
    /**
     * Comes before the phone number, e.g. "Lebih suka bercakap terus? Hubungi".
     */
    callText?: string | null;
    formTitle?: string | null;
    formSub?: string | null;
    formFine?: string | null;
    /**
     * Options in the optional "Jenis sisa" dropdown.
     */
    wasteTypes?:
      | {
          label: string;
          id?: string | null;
        }[]
      | null;
    background?: (number | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Business details, contact number and search engine settings used across the page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  businessName: string;
  logo?: (number | null) | Media;
  /**
   * Digits only, with country code and no plus sign, e.g. 601111501005. Every WhatsApp button and the phone link use this number.
   */
  whatsappNumber: string;
  /**
   * The number as shown on the page, e.g. 011-1150 1005.
   */
  phoneDisplay: string;
  locality: string;
  region: string;
  /**
   * Opens every pre-filled WhatsApp message the page builds for a visitor, e.g. "Hi Saiboss!".
   */
  whatsappGreeting: string;
  /**
   * Pre-filled message for the general WhatsApp buttons: header, floating button and footer.
   */
  defaultWhatsappMessage: string;
  /**
   * The live address without a trailing slash, e.g. https://tongrorobin.com
   */
  siteUrl: string;
  metaTitle: string;
  metaDescription: string;
  /**
   * Shown when the link is shared. Falls back to the meta description.
   */
  ogDescription?: string | null;
  /**
   * Also used as the business image in Google structured data.
   */
  ogImage?: (number | null) | Media;
  /**
   * The description in the LocalBusiness structured data.
   */
  schemaDescription?: string | null;
  footerDescription?: string | null;
  footerDescriptionEn?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "homepage_select".
 */
export interface HomepageSelect<T extends boolean = true> {
  hero?:
    | T
    | {
        tag?: T;
        heading?: T;
        sub?: T;
        primaryCta?:
          | T
          | {
              label?: T;
              message?: T;
            };
        secondaryCtaLabel?: T;
        poster?: T;
        video?: T;
      };
  figures?:
    | T
    | {
        prefix?: T;
        value?: T;
        suffix?: T;
        caption?: T;
        id?: T;
      };
  work?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lede?: T;
        items?:
          | T
          | {
              title?: T;
              description?: T;
              id?: T;
            };
        note?: T;
      };
  moment?:
    | T
    | {
        label?: T;
        text?: T;
        image?: T;
      };
  sizes?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lede?: T;
        items?:
          | T
          | {
              name?: T;
              shortName?: T;
              price?: T;
              heightFt?: T;
              widthFt?: T;
              lengthFt?: T;
              capacityM3?: T;
              hint?: T;
              uses?:
                | T
                | {
                    text?: T;
                    id?: T;
                  };
              image?: T;
              isDefault?: T;
              id?: T;
            };
        priceNote?: T;
        maxRentalDays?: T;
        help?:
          | T
          | {
              title?: T;
              text?: T;
              cta?:
                | T
                | {
                    label?: T;
                    message?: T;
                  };
            };
      };
  process?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        steps?:
          | T
          | {
              title?: T;
              text?: T;
              image?: T;
              id?: T;
            };
      };
  why?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lede?: T;
        reasons?:
          | T
          | {
              title?: T;
              text?: T;
              id?: T;
            };
        crew?:
          | T
          | {
              image?: T;
              caption?: T;
              id?: T;
            };
        credsLabel?: T;
        creds?:
          | T
          | {
              name?: T;
              type?: T;
              id?: T;
            };
      };
  coverage?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        lede?: T;
        baseName?: T;
        baseTag?: T;
        areas?:
          | T
          | {
              name?: T;
              id?: T;
            };
        note?: T;
        background?: T;
      };
  faq?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        items?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
      };
  booking?:
    | T
    | {
        eyebrow?: T;
        heading?: T;
        points?:
          | T
          | {
              text?: T;
              id?: T;
            };
        callText?: T;
        formTitle?: T;
        formSub?: T;
        formFine?: T;
        wasteTypes?:
          | T
          | {
              label?: T;
              id?: T;
            };
        background?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  businessName?: T;
  logo?: T;
  whatsappNumber?: T;
  phoneDisplay?: T;
  locality?: T;
  region?: T;
  whatsappGreeting?: T;
  defaultWhatsappMessage?: T;
  siteUrl?: T;
  metaTitle?: T;
  metaDescription?: T;
  ogDescription?: T;
  ogImage?: T;
  schemaDescription?: T;
  footerDescription?: T;
  footerDescriptionEn?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}